parameters:
- name: RunOnnxRuntimeTests
  displayName: Run Tests?
  type: boolean
  default: true

- name: DoCompliance
  displayName: Run Compliance Tasks?
  type: boolean
  default: true

- name: DoEsrp
  displayName: Run code sign tasks? Must be true if you are doing an Onnx Runtime release.
  type: boolean
  default: false

- name: IsReleaseBuild
  displayName: Is a release build? Set it to true if you are doing an Onnx Runtime release.
  type: boolean
  default: false

- name: AdditionalBuildFlags
  displayName: Additional build flags for build.py
  type: string
  default: --use_openmp

- name: OrtNugetPackageId
  displayName: Package name for nuget
  type: string
  default: 'Microsoft.ML.OnnxRuntime'

jobs:
- job: Jar_Packaging
  workspace:
    clean: all
  pool: 'Win-CPU-2019'
  condition: succeeded()
  steps:
  - checkout: self
    submodules: false
  - template: set-version-number-variables-step.yml

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact - Win x64'
    inputs:
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 43
      buildVersionToDownload: specific
      pipelineId: 142303
      artifactName: 'drop-onnxruntime-java-win-x64'
      targetPath: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact - Linux x64'
    inputs:
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 43
      buildVersionToDownload: specific
      pipelineId: 142303
      artifactName: 'drop-onnxruntime-java-linux-x64'
      targetPath: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-linux-x64'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact - MacOS x64'
    inputs:
      buildType: specific
      project: '530acbc4-21bc-487d-8cd8-348ff451d2ff'
      definition: 43
      buildVersionToDownload: specific
      pipelineId: 142303
      artifactName: 'drop-onnxruntime-java-osx-x64'
      targetPath: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-osx-x64'
 
  - task: PowerShell@2
    displayName: 'PowerShell Script'
    inputs:
      targetType: filePath
      filePath: $(Build.SourcesDirectory)\tools\ci_build\github\windows\jar_packaging.ps1
      failOnStderr: true
      showWarnings: true
      workingDirectory: '$(Build.BinariesDirectory)\java-artifact'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.BinariesDirectory)\java-artifact\onnxruntime-java-win-x64'
      artifact: 'onnxruntime-java'
      publishLocation: 'pipeline'

  - template: component-governance-component-detection-steps.yml
    parameters :
      condition : 'succeeded'


- job: Final_Jar_Testing_Windows
  workspace:
    clean: all
  pool: 'Win-CPU-2019'
  timeoutInMinutes: 60
  dependsOn:
    Jar_Packaging
  steps:
  - template: set-version-number-variables-step.yml

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Final Jar'
    inputs:
        buildType: 'current'
        artifactName: 'onnxruntime-java'
        targetPath: '$(Build.BinariesDirectory)\final-jar'

  - task: CmdLine@2
    inputs:
      script: |
        mkdir test 
        pushd test
        jar xf $(Build.BinariesDirectory)\final-jar\testing.jar
        popd
        powershell -Command "Invoke-WebRequest https://oss.sonatype.org/service/local/repositories/releases/content/org/junit/platform/junit-platform-console-standalone/1.6.2/junit-platform-console-standalone-1.6.2.jar -OutFile junit-platform-console-standalone-1.6.2.jar"
        powershell -Command "Invoke-WebRequest https://oss.sonatype.org/service/local/repositories/google-releases/content/com/google/protobuf/protobuf-java/3.9.2/protobuf-java-3.9.2.jar -OutFile protobuf-java-3.9.2.jar"
        java -jar junit-platform-console-standalone-1.6.2.jar -cp .;.\test;protobuf-java-3.9.2.jar;onnxruntime-$(OnnxRuntimeVersion).jar --scan-class-path --fail-if-no-tests --disable-banner
      workingDirectory: '$(Build.BinariesDirectory)\final-jar'

- job: Final_Jar_Testing_Linux
  workspace:
    clean: all
  pool: 'Linux-CPU'
  timeoutInMinutes: 60
  dependsOn:
    Jar_Packaging
  steps:
  - template: set-version-number-variables-step.yml
  - task: DownloadPipelineArtifact@2
    displayName: 'Download Final Jar'
    inputs:
      buildType: 'current'
      artifactName: 'onnxruntime-java'
      targetPath: '$(Build.BinariesDirectory)/final-jar'

  - task: CmdLine@2
    inputs:
      script: |
        sudo apt-get install -y openjdk-8-jdk
        sudo apt autoremove
        PATH=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin:${PATH}
        echo "Java Version"
        java --version
        mkdir test
        pushd test
        jar xf $(Build.BinariesDirectory)/final-jar/testing.jar
        popd
        wget https://oss.sonatype.org/service/local/repositories/releases/content/org/junit/platform/junit-platform-console-standalone/1.6.2/junit-platform-console-standalone-1.6.2.jar -P ./
        wget https://oss.sonatype.org/service/local/repositories/google-releases/content/com/google/protobuf/protobuf-java/3.9.2/protobuf-java-3.9.2.jar -P ./
        LD_LIBRARY_PATH=./test:${LD_LIBRARY_PATH}
        java -jar ./junit-platform-console-standalone-1.6.2.jar -cp .:./test:./protobuf-java-3.9.2.jar:./onnxruntime-$(OnnxRuntimeVersion).jar --scan-class-path --fail-if-no-tests --disable-banner
      workingDirectory: '$(Build.BinariesDirectory)/final-jar'

- job: Final_Jar_Testing_MacOs
  workspace:
    clean: all
  pool: 
    vmImage: 'macOS-10.14'
  timeoutInMinutes: 60
  dependsOn:
    Jar_Packaging
  steps:
  - template: set-version-number-variables-step.yml

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Final Jar'
    inputs:
      buildType: 'current'
      artifactName: 'onnxruntime-java'
      targetPath: '$(Build.BinariesDirectory)/final-jar'

  - task: CmdLine@2
    inputs:
        script: |
          echo "Java Version"
          java --version
          mkdir test
          pushd test
          jar xf $(Build.BinariesDirectory)/final-jar/testing.jar
          popd
          wget https://oss.sonatype.org/service/local/repositories/releases/content/org/junit/platform/junit-platform-console-standalone/1.6.2/junit-platform-console-standalone-1.6.2.jar -P ./
          wget https://oss.sonatype.org/service/local/repositories/google-releases/content/com/google/protobuf/protobuf-java/3.9.2/protobuf-java-3.9.2.jar -P ./
          sudo xcode-select --switch /Applications/Xcode_10.app/Contents/Developer
          brew install libomp
          DYLD_LIBRARY_PATH=./test:${DYLD_LIBRARY_PATH}
          java -jar ./junit-platform-console-standalone-1.6.2.jar -cp .:./test:./protobuf-java-3.9.2.jar:./onnxruntime-$(OnnxRuntimeVersion).jar --scan-class-path --fail-if-no-tests --disable-banner
        workingDirectory: '$(Build.BinariesDirectory)/final-jar'
